#!/bin/bash

# environment hook for terraform plugin
# prepends plugin `bin` dir to $PATH

set -ueo pipefail

export TERRAFORM_VERSION="${TERRAFORM_VERSION:-1.0.1}"
export OPA_VERSION="${OPA_VERSION:-0.30.1}"


# Make everyhing in the `bin` dir available in $PATH
DIR="$(cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd)"
export PATH="$DIR/../bin:$PATH"
export TERRAFORM_PLUGIN_DIR=$DIR/..


echo "___ : checking if the provided command is allowed.."

if [[ "${BUILDKITE_COMMAND}" != "buildkite-agent pipeline upload" ]] | [[ "${BUILDKITE_COMMAND}" != "tf_version" ]] | [[ "${BUILDKITE_COMMAND}" != "tf_plan" ]] | [[ "${BUILDKITE_COMMAND}" != "tf_apply" ]]; then
  echo "Command not allowed: ${BUILDKITE_COMMAND}."
  exit 1
fi
